# Generated by Django 2.0.3 on 2018-03-30 15:34

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='Cost',
        ),
        migrations.AddField(
            model_name='mobile',
            name='mobile_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11, verbose_name='Cost'),
        ),
    ]
