# Generated by Django 2.0.3 on 2018-03-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='Lens',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
