# Generated by Django 2.0.3 on 2018-03-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20180327_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='Resolution',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
