# Generated by Django 2.0.3 on 2018-03-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20180330_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_battery',
            new_name='battery',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='moblie_camera',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_cost_currency',
            new_name='cost_currency',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_display',
            new_name='display',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_extraFeature',
            new_name='extraFeature',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_processor',
            new_name='processor',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_software',
            new_name='software',
        ),
    ]
