# Generated by Django 2.0.3 on 2018-03-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20180327_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mobile',
            name='mobile_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Company'),
        ),
    ]
