# Generated by Django 2.0.3 on 2018-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_auto_20180328_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='mobile_extraFeature',
        ),
        migrations.AddField(
            model_name='mobile',
            name='mobile_extraFeature',
            field=models.ManyToManyField(blank=True, to='compare.extraFeatures'),
        ),
    ]
